apiVersion: demo.upbound.io/v1alpha1
kind: ClusterClaim
metadata:
  name: a-team
  namespace: a-team
spec:
  id: a-team
  compositionSelector:
    matchLabels:
      provider: google
      cluster: gke
  parameters:
    nodeSize: small
